# Generated by Django 4.2.1 on 2023-05-31 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorianev', models.CharField(max_length=40, unique=True, verbose_name='Kategória neve')),
            ],
        ),
        migrations.CreateModel(
            name='Teszt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerdes', models.CharField(max_length=150, unique=True, verbose_name='Kérdés')),
                ('v1', models.CharField(max_length=150, verbose_name='1. válasz')),
                ('v2', models.CharField(max_length=150, verbose_name='2. válasz')),
                ('v3', models.CharField(max_length=150, verbose_name='3. válasz')),
                ('v4', models.CharField(max_length=150, verbose_name='4. válasz')),
                ('helyes', models.CharField(default=models.CharField(max_length=150, verbose_name='1. válasz'), max_length=150, verbose_name='Helyes válasz')),
                ('kategoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizsga.kategoria', verbose_name='Kategória')),
            ],
        ),
    ]
